# Generated by Django 4.2.1 on 2023-05-26 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GaragemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'garagem',
            },
        ),
        migrations.CreateModel(
            name='UsuarioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('garagens_em_uso', models.ManyToManyField(blank=True, related_name='usuarios', to='app.garagemmodel')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='CarroModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=254)),
                ('modelo', models.CharField(max_length=254)),
                ('cor', models.CharField(max_length=254)),
                ('dono', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frota', to='app.usuariomodel')),
                ('estacionado_em', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carros_estacionados', to='app.garagemmodel')),
            ],
            options={
                'db_table': 'carro',
            },
        ),
    ]
