# Generated by Django 4.2.1 on 2023-05-24 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carromodel',
            options={'ordering': ['placa']},
        ),
        migrations.AlterModelOptions(
            name='garagemmodel',
            options={'ordering': ['numero']},
        ),
        migrations.AlterModelOptions(
            name='usermodel',
            options={'ordering': ['nome']},
        ),
        migrations.RemoveField(
            model_name='carromodel',
            name='nome',
        ),
        migrations.AddField(
            model_name='carromodel',
            name='dono',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='colecao', to='app.usermodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carromodel',
            name='garagem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='estacionados', to='app.garagemmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carromodel',
            name='placa',
            field=models.CharField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='carromodel',
            table='carro',
        ),
        migrations.AlterModelTable(
            name='usermodel',
            table='user',
        ),
    ]
