# Generated by Django 4.2.1 on 2023-05-24 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_carromodel_options_alter_garagemmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carromodel',
            name='dono',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colecao', to='app.usermodel'),
        ),
        migrations.AlterField(
            model_name='carromodel',
            name='garagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estacionados', to='app.garagemmodel'),
        ),
    ]
